title: Eleni Nisioti
subtitle: My academic and personal website
description: >- # this means to ignore newlines until "baseurl:"
  

url: https://eleninisioti@github.io "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Blog
      url: /blog



# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile.png
author_avatar: eleninisioti.png
author: Eleni Nisioti
author_bio: Hi, my name is Eleni Nisioti and this is my academic and somewhat personal website. I am a researcher in Artificial Intelligence, working
  primarily on multi-afgent reinforcement learning, evolutionary optimization and complex systems.
author_email: "elennisioti@gmail,com"
author_location: France
#author_website_url: ""
typewrite-text: learning in multi-agent systems
hero_cover_img: sample_cover.jpg # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Experiences
author_work_experiences:
            - company_name: Flowers, Inria
              company_logo: inria.png
              company_url: https://flowers.inria.fr/
              designation: Post-doctoral researcher
              description: Worked on various projects in the areas of multi-agent reinforcement learning and evolutionary optimization
              visibility: true

# Education
author_education_details:
              - college_logo: essex.jpeg
                college_name: University of Essex
                college_url:
                college_degree: PhD
                description:
                visibility: true

              - college_logo: auth.png
                college_name: Aristotle Univesity of Thessaloniki
                college_url:
                college_degree: Diploma of Electriral and Computer Engineering
                description:
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: sapiens_structures.gif
                project_title: "Social Network Structure Shapes Innovation: Experience-sharing in RL with SAPIENS"
                project_description: Reinforcement learning agents play the Little Alchemy 2 game. Will sharing experiences help them and who should they share with?
                project_url: https://github.com/eleninisioti/SAPIENS
                project_code_url: https://arxiv.org/abs/2206.05060
                citation: "Eleni Nisioti, Mateo Mahaut, Pierre-Yves Oudeyer, Ida Momennejad, Clément Moulin-Frier. “Social network structure shapes innovation: experience sharing in RL with SAPIENS. https://arxiv.org/abs/2206.05060”."
                visibility: true

              - project_thumbnail: fig8_NF.gif
                project_title: "Plasticity and evolvability under environmental variability: the joint role of fitness-based selection and niche-limited competition"
                project_description: A population evovles its plasticity and adaptability in an environment consisting of niches whose quality varies with time
                project_url: https://arxiv.org/abs/2202.08834
                project_code_url: https://github.com/eleninisioti/ClimateAndLearning
                citation: "Eleni Nisioti, Clément Moulin-Frier. “Plasticity and evolvability under environmental variability: the joint role of fitness-based selection and niche-limited competition”, GECCO, July 2022, Boston"
                visibility: true

              - project_thumbnail: framework.png
                project_title: "Grounding an Ecological Theory of Artificial Intelligence in Human Evolution"
                project_description:  A conceptual framework for grounding research in AI in what we know about our own species
                project_url: https://hal.science/hal-03446961/
                #project_code_url: https://github.com/eleninisioti/ClimateAndLearning
                citation: "Eleni Nisioti and Katia Jodogne-del Litto and Clément Moulin-Frier, “Grounding an Ecological Theory of Artificial Intelligence in Human Evolution”, NeurIPS 2021- Conference on Neural Information Processing Systems / Workshop: Ecological Theory of Reinforcement Learning, Dec 2021"
                visibility: true






# social links
twitter_username: nisioti_eleni
github_username:  eleninisioti
medium_username: elennisioti
telegram_username: johndoe


#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
#hyvor_talk_website_id: 476

# wakatime username (coding activity)
#wakatime_username: sujaykundu777

# mailchimp embedded form url (newsletter):
#mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# contact form - (choose formspress or getform)
# getform_endpoint: 83b703c3-9e47-4df4-ac55-e24d7eb02abc
formspree_email: elennisioti@gmail.com

# releases - widget can be (sidebar, modal or embed)
#olvy_organization: devlopr
#olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'


##collections:
#  products:
#    output: true
#  authors:
#    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug
  -
    scope:
      path: 'assets/**'
    values:
      sitemap: false

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/bower_components/isotope-layout/README.md
  - assets/bower_components/icono/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
  - assets/bower_components/ghosthunter/README.md
  - assets/bower_components/nanobar/README.md
  - assets/bower_components/lightgallery/demo/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
  - assets/bower_components/jquery-mousewheel/README.md
  - assets/bower_components/get-size/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
  - assets/bower_components/desandro-matches-selector/README.md
  - assets/bower_components/ev-emitter/README.md
  - assets/bower_components/font-awesome/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
  - assets/bower_components/ghosthunter/example/Index.html
  - assets/bower_components/lightgallery/test/lightgallery.html
  - assets/bower_components/masonry-layout/README.md
  - assets/bower_components/imagesloaded/README.md


destination: ./build
